services:
  vhs-rental:
    container_name: vhs-rental
    build: .
    ports:
      - '3001:3000'
    depends_on:
      - vhs-database
    links:
      - vhs-database
    environment:
      SEED_DB: 1
      JWT_SECRET: topSecret51
      DATABASE_URL: postgres://postgres:postgres@vhs-database/vhs-database
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost/vhs-test-database

  vhs-database:
    container_name: vhs-database
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vhs-database
